const images = [
  'https://i.ytimg.com/vi/oftolPu9qp4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPHsTTR46ste2aIKx5IbiGfP3V8Q',
  'https://i.ytimg.com/vi/oftolPu9qp4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPHsTTR46ste2aIKx5IbiGfP3V8Q',
  'https://i.ytimg.com/vi/7NK_JOkuSVY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBsOlaEY_H9Ov51s92Hw_icS_teyw',
  'https://i.ytimg.com/vi/0V0t1ilC97w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCcvP0jUieJtb5is6z_lGzIaQ3W8Q',
  'https://i.ytimg.com/vi/y1cBhJLNNXU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBhlEf5yAVM-KTGzbx3Js740KOUBQ',
  'https://i.ytimg.com/vi/lzEop75AeOk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfiwE94Due89kqlo8e2nj7Y7d5lg',
  'https://i.ytimg.com/vi/E91pJYO_s7I/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_g6AArgIigIMCAAQARgnIFQocjAP&rs=AOn4CLA_5yJqkbSDD5_G_XVw8blPWVjL5Q',
  'https://i.ytimg.com/vi/HpLVgAt4aQQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAlOCgEOFUaVHD16N0ctgG_Ggan9g',
  'https://i.ytimg.com/vi/hYjHhqLSiN4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB28yEbsoOYBZ2ZUCOv8KCp6OA4gQ',
  'https://i.ytimg.com/vi/7u4mT7Q3Bb8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD_8Pnh4oQZATIfLgEs7dTVj_Syow',
  'https://i.ytimg.com/vi/iIyrLRixMs8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDhJr9rl7F9v_FTY2jz14n5p9jr1g',
  'https://i.ytimg.com/vi/CtM3uMDnEuY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUzw12ata_qlu4lGtb1jNOuAFwyg',
  'https://i.ytimg.com/vi/4DfVxVeqk2o/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDctptGaZSkhWTIPP1CY0nSsrKAZg',
  'https://i.ytimg.com/vi/Lr1dRlhW5T8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDIw0V2dm_lVcHFwiTAuf-yfanCZQ',
  'https://i.ytimg.com/vi/EdXMjdIdFxo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrpWDWtoYwT8rEtOI0_a3klqzIgA',
  'https://i.ytimg.com/vi/pw9RBn3O1jY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBY3PNV_za36-8MMdx-tk1FAIHi1w',
  'https://i.ytimg.com/vi/F2uO_InN86c/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAcq0L02IHYrYckVyaqbMaIm9cB1w',
  'https://i.ytimg.com/vi/iYxJOBYaYGg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB1UaklkBmpKMEqtyh7J4ZHrRrNfg',
  'https://i.ytimg.com/vi/2bpMSpFTdzM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDIhfZHM6W-RWVKqIwbFZgTAridMA',
  'https://i.ytimg.com/vi/pYqky795R1s/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIGUoZTAP&rs=AOn4CLCH1Wm4xbLhZXODb73H9GDf7iCW8g',
  'https://i.ytimg.com/vi/IgDCPDpgiSo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCAJt-7VF9qwpzTGfZiKbme6TKeoA',
  'https://i.ytimg.com/vi/TpyvoZq6M-Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBW6YliC4GOpdw4CTlvLIHpJU2qXw',
  'https://i.ytimg.com/vi/8omBAsWVc5c/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQP_-re3jZ0sj8Yn7ijPK78cKBPA',
  'https://i.ytimg.com/vi/NOHE_cVlkHE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAeB0hWtFGTaBkJYLD4doYRkN24VQ',
  'https://i.ytimg.com/vi/qN3wfuPYTI4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAGnWHURfIfJ6Zjrva_PjBVNgUCTA',
  'https://i.ytimg.com/vi/Nlw6a-qhKEI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBDqynnuCzWkIdMpSNuGZey2prKog',
  'https://i.ytimg.com/vi/NJTvniEcpaI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBp7PEmU1wqiSWMfAl0NE7DZ7gGtg',
  'https://i.ytimg.com/vi/bjjC1-G6Fxo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwdkdmkWHk60eGzO_oz71Sgm8Qmw',
  'https://i.ytimg.com/vi/HfMTwkVQohM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAnOlvTqFKM7_-Q6z9MO0bKlENyvQ',
  'https://i.ytimg.com/vi/qMXESlny4-I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCH0oJ8uZGC8xpukTH-HTdrxyyU3w',
];

const titles = [
  'PinkPantheress, Ice Spice - Boy’s a liar Pt. 2 (Official Video)',
  'Lost [Official Music Video] - Linkin Park',
  'Sam Smith, Kim Petras - Unholy (Live at The BRIT Awards 2023)',
  'beabadoobee - Glue Song',
  'Naiyo Lagda - Kisi Ka Bhai Kisi Ki Jaan | Salman Khan & Pooja Hegde | Himesh R, Kamaal K, Palak M',
  'Lovejoy - Call Me What You Like (OFFICIAL VIDEO)',
  'AB - Plugged In w/ Fumez The Engineer | @MixtapeMadness',
  "Sam Smith - I'm Not Here To Make Friends",
  'K-Trap - Interlude',
  'Depeche Mode - Ghosts Again (Official Video)',
  'Central Cee - Me and You (Lyrics)',
  '52 Bars  (Official Video) Karan Aujla | Ikky | Four You EP | First Song | Latest Punjabi Songs 2023',
  'Tzanca Uraganu si Mr Juve - Alo baza baza [video oficial] 2023',
  'Zack Knight - Bollywood Medley Pt 9',
  'Abra Cadabra - 15 Years (Official Video)',
  'Abra Cadabra - For You (Official Video)',
  'Luis Gabriel - Orice Pana La Ea (Guest: @Haziran, vocea inimii mele)',
  'Lizzy McAlpine - ceilings (official video)',
  'Lana Del Rey - A&W (Audio)',
  'Harry Styles - As It Was (Live at The BRIT Awards 2023)',
  'Clavish - B22 Money (Official Video)',
  'Fresh Home Freestyle',
  'Haseeb Haze X Muki | Kahani Suno 2.0 | Kaifi Khalil (OST COVER)',
  'LEO - Bloody Sweet Promo | Thalapathy Vijay | Lokesh Kanagaraj | Anirudh',
  'Dizzy DROS - M3A L3ECHRANE (Official Music Video)',
  'Blanco - Daily Duppy  | GRM Daily',
  'James Arthur - A Thousand Years (Christina Perri Cover)',
  'Full Video: Jimikki Ponnu (Tamil) Varisu | Thalapathy Vijay | Thaman S | Vamshi Paidipally',
  'Falling In Reverse - "Watch The World Burn"',
];

const channels = [
  'Pinkpantheress',
  'Linkin Park',
  'SAM SMITH',
  'Beabadoobee',
  'Zee Music Company',
  'Lovejoy',
  'Mixtape Madness',
  'SAM SMITH',
  'K-Trap',
  'Depeche Mode',
  'Central Cee',
  'Karan Aujla',
  'Tzanca Uraganu',
  'iamzackknight',
  'Abra Cadabra',
  'Abra Cadabra',
  'Luis Gabriel',
  'Lizzy McAlpine',
  'Lana Del Rey',
  'Harry Styles',
  'Clavish',
  'Various Artists - Topic',
  'Haseeb Haze',
  'Sony Music India',
  'Dizzy DROS',
  'GRM Daily',
  'James Arthur',
  'T-Series',
  'Epitaph Records',
];

const meta = [
  { views: '14 Tr lượt xem', publishTime: '12 ngày trước' },
  { views: '14 Tr lượt xem', publishTime: '6 ngày trước' },
  { views: '2,6 Tr lượt xem', publishTime: '4 ngày trước' },
  { views: '930 N lượt xem', publishTime: '1 ngày trước' },
  { views: '38 Tr lượt xem', publishTime: '3 ngày trước' },
  { views: '1,6 Tr lượt xem', publishTime: '5 ngày trước' },
  { views: '867 N lượt xem', publishTime: '6 ngày trước' },
  { views: '11 Tr lượt xem', publishTime: '2 tuần trước' },
  { views: '44 N lượt xem', publishTime: '1 ngày trước' },
  { views: '5,3 Tr lượt xem', publishTime: '6 ngày trước' },
  { views: '946 N lượt xem', publishTime: '6 ngày trước' },
  { views: '22 Tr lượt xem', publishTime: '13 ngày trước' },
  { views: '2,8 Tr lượt xem', publishTime: '5 ngày trước' },
  { views: '1,4 Tr lượt xem', publishTime: '10 ngày trước' },
  { views: '74 N lượt xem', publishTime: '1 ngày trước' },
  { views: '107 N lượt xem', publishTime: '2 ngày trước' },
  { views: '3,1 Tr lượt xem', publishTime: '12 ngày trước' },
  { views: '354 N lượt xem', publishTime: '1 ngày trước' },
  { views: '935 N lượt xem', publishTime: '1 ngày trước' },
  { views: '1,6 Tr lượt xem', publishTime: '3 ngày trước' },
  { views: '133 N lượt xem', publishTime: '3 ngày trước' },
  { views: '105 N lượt xem', publishTime: '8 ngày trước' },
  { views: '52 N lượt xem', publishTime: '1 ngày trước' },
  { views: '44 Tr lượt xem', publishTime: '13 ngày trước' },
  { views: '5,2 Tr lượt xem', publishTime: '2 ngày trước' },
  { views: '717 N lượt xem', publishTime: '10 ngày trước' },
  { views: '134 N lượt xem', publishTime: '1 ngày trước' },
  { views: '4,5 Tr lượt xem', publishTime: '4 ngày trước' },
  { views: '8,7 Tr lượt xem', publishTime: '2 tuần trước' },
];

const ids = [
  'oftolPu9qp4',
  '7NK_JOkuSVY',
  '0V0t1ilC97w',
  'y1cBhJLNNXU',
  'lzEop75AeOk',
  'HpLVgAt4aQQ',
  'E91pJYO_s7I',
  'hYjHhqLSiN4',
  '7u4mT7Q3Bb8',
  'CtM3uMDnEuY',
  'iIyrLRixMs8',
  'Lr1dRlhW5T8',
  'pw9RBn3O1jY',
  'EdXMjdIdFxo',
  '4DfVxVeqk2o',
  'F2uO_InN86c',
  '2bpMSpFTdzM',
  'iYxJOBYaYGg',
  'pYqky795R1s',
  'TpyvoZq6M-Y',
  'IgDCPDpgiSo',
  '8omBAsWVc5c',
  'NOHE_cVlkHE',
  'Nlw6a-qhKEI',
  'qN3wfuPYTI4',
  'bjjC1-G6Fxo',
  'HfMTwkVQohM',
  'NJTvniEcpaI',
  'qMXESlny4-I',
];
